### ISSUE TITLE
Different colors for buttons

### ISSUE THREAD

**Issue by hajo4** [Germanunkol/trAInsported#107]
would be nice, e.g.:
* red for Quit/Exit/Abort/Return - type buttons
* blue for Settings/OpenFolder/GameMode - buttons
* yellow for "already done" (tutorials) and
 "this one was selected the last time"  
 (e.g. Challenge in main-menu, and in there
  the most-recently used challenge-map)

**Comment by Germanunkol** [comment]
I have little time in the following months and would like to focus on more important issues. Also, I kinda like the reduced palette...

Thanks for the suggestion, though!
