### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by sammuel86** [Germanunkol/trAInsported#111]
trying to build your program and im getting alot of these errors: http://prntscr.com/6oer9r

any ideas on the cuase?

**Comment by Germanunkol** [comment]
Hm,
I'm confused. trAInsported is written in Lua, so no building is necessary.
Instead, you need to install Löve2D and run the program with it.

What OS are you using?
Easiest way to get the game to run is probably to get it from the download page:
http://trainsportedgame.no-ip.org/download.php
Version 5 (the newest version) should run fine with Löve 0.9.
