### ISSUE TITLE
Error in Tutorial #2

### ISSUE THREAD

**Issue by incinirate** [Germanunkol/trAInsported#113]
Scripts/ai.lua:410: attempt to index local 'result' (a number value)

Traceback:

main.lua:801: in function '__index'
Scripts/ai.lua:410: in function 'foundPassengers'
Scripts/train.lua:526: in function 'moveSingleTrain'
Scripts/train.lua:596: in function 'moveAll'
main.lua:658: in function 'update'
[C]: in function 'xpcall'

My code: 
```Lua
-- Tutorial 3: Be smart!

function ai.init()
	buyTrain(3,1)
end

function ai.chooseDirection(train,directions)
	if train.passenger == nil then
		print(train.name.." carries no passenger.")
		return "S"
	else
	    print(train.name.." carries "..train.passenger.name)
	    if train.passenger.destX < train.x then
	    	return "W"
	    else
	        return "E"
	    end
	end
end

function ai.foundPassengers(train, passengers)
	if train.ID == 1 then
		for k,v in ipairs(passengers) do
			if v.destX > train.x then
				return k
			end
		end
	else
	    for k,v in ipairs(passengers) do
			if v.destX < train.x then
				return k
			end
		end
	end
end

function ai.foundDestination(train)
	dropPassenger(train)
end

function ai.enoughMoney()
	buyTrain(1,3)
end
```

**Comment by Germanunkol** [comment]
Hi, thanks for reporting!

The problem with your code is that you should return the passenger, (which is in v) and not the index (which is k) in the two lines "return k" in ai.foundPassenger.

However, even if you return the wrong thing, it shouldn't crash, of course!
I'll try to fix it...
