### ISSUE TITLE
Game don't start

### ISSUE THREAD

**Issue by szymex73** [Germanunkol/trAInsported#115]
When i start the game i have window with this message:
Error: Scripts/menu.lua:23: attempt to index field 'window' (a nil value)
stack traceback:
        Scripts/menu.lua:23: in main chunk
        [C]: in function 'require'
        main.lua:371: in main chunk
        [C]: in function 'require'
        [string "boot.lua"]:331: in function <[string "boot.lua"]:227>
        [C]: in function 'xpcall'

My pc:
Linux Mine 17 KDE,
1GB RAM
Intel Centrino Duo

**Comment by jklmnn** [comment]
You are running löve 0.8 but you need 0.9.
Try installing 0.9 from a newer Ubuntu repo or the Debian stable repo.

**Comment by Germanunkol** [comment]
Yes, you should be using 0.9.

Sorry for the weird error message, I really should catch that and print a nicer warning.

**Comment by jklmnn** [comment]
@Germanunkol try taking a look at #114 ;)

**Comment by Germanunkol** [comment]
Uh, Sorry, totally forgot about that. Will check it out!

**Comment by Germanunkol** [comment]
Should now display an error message if the version is wrong. Thanks @jklmnn for the pull request!
