### ISSUE TITLE
port to love 0.10

### ISSUE THREAD

**Issue by Kaligule** [Germanunkol/trAInsported#120]
On some distributions it is suprisingly hard to get old packages. It would be cool if trAInsported could run on the up-to-date game-engine.

**Comment by Kaligule** [comment]
Acctually the game works fine in 0.10 if the artificial test for the version of love is disabled.

**Comment by Germanunkol** [comment]
Okay, thanks for testing, I will change the version check to also allow 0.10.
What system are you on? My systems all still install 0.9...

**Comment by Kaligule** [comment]
Arch linux.

**Comment by ZoeShi** [comment]
hello
I have linux mint and had installed the game in version 5.3 but if I  start the game I get the error that this game is write for love version 0.9 and I have version 10 installed and can't install a lower version.

**Comment by Germanunkol** [comment]
Ah, I still have 0.9.1 here :( ... on Ubuntu. I should really build my own Löve.
As Kaligule mentioned, you can disable the version check in the code.
I can't test it right now, but try to open the main.lua and then comment out the following lines (for example by enclosing them in --[[ and ]]--)
`if love._version_major ~= LOVE_VERSION_MAJOR or love._version_minor ~= LOVE_VERSION_MINOR then
	
		error( "Wrong version of the Löve engine detected. " ..
				"TrAInsported was programmed for version '" ..
				LOVE_VERSION_MAJOR .. "." .. LOVE_VERSION_MINOR .. "'.\n" ..
				"Get the engine at https://love2d.org/.")
	end`

**Comment by jklmnn** [comment]
We maybe shouldn't disable the test, but test for the minimum version instead of an exact one. So change it to >= 0.9 instead of == 0.9.

It is not only hard to get a old version but also a new one.

**Comment by ZoeShi** [comment]
can you fix it maybe on the deb package version 5.3 than can I easy install it

**Comment by jklmnn** [comment]
That needs to be done in the `debian/control` file. The depency should be changed to `love (>=0.9.1)` then.

**Comment by ZoeShi** [comment]
this is standing in the debian/control file but I get the same error

**Comment by jklmnn** [comment]
The debian/control only controls if you can install the package. It doesn't have any influence to the functionality. You may try the Pull Request I created.

**Comment by ZoeShi** [comment]
can you pack this in a deb package

**Comment by Germanunkol** [comment]
Please try [this deb package](http://germanunkol.de/trainsported/download/trainsported-5.4_all.deb).

**Comment by Germanunkol** [comment]
Sorry, didn't mean to close.

**Comment by ZoeShi** [comment]
thank you very much this game is now working

**Comment by Germanunkol** [comment]
Great! Have fun :)

Thanks again @jklmnn for the quick fix!

**Comment by ZoeShi** [comment]
I have a question in the tutorial i shoult write print("Hello TrAIns!") wen I reload the match I get no ai.init() fount for TutorialAI1

**Comment by Germanunkol** [comment]
Yes, but the tutorial works, right?
The no "ai.init found" is only a warning, which is not relevant at this point.
I admit this isn't very pretty, but the warning might help later on, so I believe it makes sense to leave it there.

**Comment by ZoeShi** [comment]
the hello trains is not  there and it does nothing

**Comment by ZoeShi** [comment]
sorry my mistake I had forget to save and thanks I was confused about the warning
