### ISSUE TITLE
broken server matches

### ISSUE THREAD

**Issue by solAIr1** [Germanunkol/trAInsported#52]
While I was watching some of the live matches I noticed that some of them seem to be broken. 

The train's are not moved properly (they seem to be teleporting) and at the end the time limit runs out but the round does not end. Instead the countdown switches to 24 hours. At some point of time these matches seem to be killed by the server.

Those matches are normally won by the AI that managed to drop around 3 passengers.
(while a "normal running" match requires at least a two digit number of passengers to win)

**Comment by Germanunkol** [comment]
Moved to new server. Have not seen the issue since.
