### ISSUE TITLE
Crash: "Live" / bad packet

### ISSUE THREAD

**Issue by hajo4** [Germanunkol/trAInsported#92]
Right after pressing "Live", I got this crash:
![err_2014-02-27_addpacket](https://f.cloud.github.com/assets/5838618/2286838/04d5b1ea-9fe6-11e3-9595-106a5caa2758.jpg)
This is still on v4.

**Comment by Germanunkol** [comment]
Should be fixed in 5fd36232ab728fd5cb4568c3e23737cf0e48070f (if not earlier).
