### ISSUE TITLE
Host the official website via a durable solution

### ISSUE THREAD

**Issue by bkil** [Germanunkol/trAInsported#95]
This games looks fantastic, but I'm a bit worried about its future.

I'd recommend serving the site directly from GitHub, like so: https://pages.github.com/
Or use any free web hosting solution you like.
The idea would be to host and cache as much information as possible in a durable and scalable way on the official site.
You can still embed the current match widget in an iframe from no-ip.

I would also find it useful to find a bit more introduction there, and links to reviews all in one place.

**Comment by bkil** [comment]
Hi! Sorry, it looks like I missed your response. I though I would get an e-mail about it or something like that. So I'm not at all worried about the speed. Although, it can be a bit slow sometimes. In my opinion, this is a nice game concept which deserves to have its place in history. For this, you need a domain or at least a stable URL. A free subdomain is also good, though I guess the address of the current redirect could be okay if you can keep it alive for at least 5-10 more years. I don't consider dyndns a durable solution. I recall having been greeted with an empty or garbled page a few times in the past when opening trainsported, and that is not very professional. What my top comment was about to maybe create a new static site (even by copy&paste), host it at a durable location and embed dynamic content from any foreign server of your liking. If the game server or SQL is down, the visitors could still get information about your fine work, review screenshots, some recent matches, scores, reviews, install the game, etc. And maybe by the time they've gone through all this, your game server could be up and running again. I understand that you are doing this as a hobby project, but the essence of my recommendation doesn't cost any money. Keep up the good work!

**Comment by Germanunkol** [comment]
Done. Game can be reached via the old http://trainsportedgame.no-ip.org or the new http://germanunkol.de/trainsported.
The site is now hosted at germanunkol.de, which is my own rented server. Should be much quicker now. As for professionality, I think you're right and the non-free domain is a step in the right direction. I will also keep updating the website (germanunkol.de), so it will hopefully look more professional as well.

Thanks again for the feedback!
